-- CreateTable
CREATE TABLE `Domain` (
	`id` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	`slug` VARCHAR(24) NOT NULL,
	`updated_by` INTEGER UNSIGNED NOT NULL,
	`updated` DATETIME(3) NOT NULL,
	`created` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
	`deleted` DATETIME(3) NULL,
	`archived` DATETIME(3) NULL,
	UNIQUE INDEX `Domain_slug_key`(`slug`),
	PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;